version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(pip)"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:15"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(docker)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(actions)"